"""add_nutrition_tables

Revision ID: 1929033ad8e5
Revises: 4a168269a7f4
Create Date: 2026-06-06 10:47:18.573736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1929033ad8e5'
down_revision: Union[str, Sequence[str], None] = '4a168269a7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('target_calories', sa.Float(), nullable=True),
    sa.Column('target_protein', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_logs_log_date'), 'nutrition_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_user_id'), 'nutrition_logs', ['user_id'], unique=False)
    op.create_table('nutrition_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bmr', sa.Float(), nullable=True),
    sa.Column('tdee', sa.Float(), nullable=True),
    sa.Column('activity_multiplier', sa.Float(), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('target_calories', sa.Float(), nullable=True),
    sa.Column('target_protein', sa.Float(), nullable=True),
    sa.Column('target_carbs', sa.Float(), nullable=True),
    sa.Column('target_fats', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_profiles_user_id'), 'nutrition_profiles', ['user_id'], unique=True)
    op.create_table('user_equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_equipment_user_id'), 'user_equipment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_equipment_user_id'), table_name='user_equipment')
    op.drop_table('user_equipment')
    op.drop_index(op.f('ix_nutrition_profiles_user_id'), table_name='nutrition_profiles')
    op.drop_table('nutrition_profiles')
    op.drop_index(op.f('ix_nutrition_logs_user_id'), table_name='nutrition_logs')
    op.drop_index(op.f('ix_nutrition_logs_log_date'), table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    # ### end Alembic commands ###
